src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mailing_First_Name__c</fullName>
        <formula>If(ISBLANK(Preferred_First_Name__c),FirstName, Preferred_First_Name__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing First Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>UST_Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Visit/Event</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Not Planning to Attend</fullName>
                    <isActive>false</isActive>
                    <label>Not Planning to Attend</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/USTEventParkingPassController.cls
/**
 * Created by dahl3702 on 5/1/2018.
 */

public with sharing class USTEventParkingPassController {
    public String couponOut { get; set; }
    public String firstName { get; set; }
    public String warning { get; set; }
    private USTEventShared USTShare = new USTEventShared();


    public USTEventParkingPassController() {
        warning = '';
        couponOut = '';
        String regId = ApexPages.currentPage().getParameters().get('regId');
        Datetime todaysDateTime = USTShare.adjustForCenteralTime(Datetime.now());
        Date todaysDate = date.newinstance(todaysDateTime.year(), todaysDateTime.month(), todaysDateTime.day());
        if (!String.isBlank(regId)) {
            UST_Event_Registration__c visitor = [SELECT Date__c, Contact__r.Name, Contact__r.Mailing_First_Name__c, Status__c FROM UST_Event_Registration__c WHERE id = :regId][0];
            if (visitor != null) {
                if (todaysDate <= visitor.Date__c && visitor.Status__c != 'Started' && visitor.Status__c != 'Cancelled') {
                    couponOut += '<p>NAME:&nbsp; ' + visitor.Contact__r.Name + '</p>';
                    couponOut += '<p>DATE VALID:&nbsp; ' + visitor.Date__c.format() + '</p>';
                    firstName = visitor.Contact__r.Mailing_First_Name__c;

                } else {
                    warning = 'Sorry, this parking permit has expired.';
                }
            }
        } else {
            warning = 'Sorry, We could not find your parking permit ID.';
        }
    }
}