src/objects/UST_Event__c.object
<CustomObject>
    <description>Parent Event object to setup individual Event Sessions</description>
    <fields>
        <fullName>Event_Footer__c</fullName>
        <description>Footer that follows through event process. Can contain contact information for issues and information</description>
        <inlineHelpText>Footer that follows through event process. Can contain contact information for issues and information</inlineHelpText>
        <label>Event Footer</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Submit_Description__c</fullName>
        <description>This text appears at the top of the submit page where confirmation of selections is given and the user submits their registration.</description>
        <inlineHelpText>This text appears at the top of the submit page where confirmation of selections is given and the user submits their registration.</inlineHelpText>
        <label>Event Submit Description</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Submit_Title__c</fullName>
        <description>Title that appears on the event submit registration page</description>
        <inlineHelpText>Title that appears on the event submit registration page</inlineHelpText>
        <label>Event Submit Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <defaultValue>&apos;CastorTemplate2017&apos;</defaultValue>
        <description>Chose a pre-programmed template for your event site</description>
        <inlineHelpText>Chose a pre-programmed template for your event site</inlineHelpText>
        <label>Template</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CastorTemplate2017</fullName>
                </value>
                <value>
                    <fullName>OPUSTemplate2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event</label>
    <nameField>
        <label>Event Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UST Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointment_Type__c.object
<CustomObject>
    <description>List of available appointments for a session</description>
    <fields>
        <fullName>Appointment_Category__c</fullName>
        <label>Appointment Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Appointment_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Appointment_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Appointment_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UST_Event__c</fullName>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Appointment Types</relationshipLabel>
        <relationshipName>UG_Event_Appointment_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment Type</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>UG Event Appointment Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointment Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <fields>
        <fullName>Appointment_Category__c</fullName>
        <label>Appointment Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Appointment_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Appointment_Title__c</fullName>
        <description>Display title of appointment</description>
        <inlineHelpText>Display title of appointment</inlineHelpText>
        <label>Appointment Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Appointment_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Appointment_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Appointment_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Thad Appointment Definition</inlineHelpText>
        <label>Event Appointment Type</label>
        <referenceTo>UST_Event_Appointment_Type__c</referenceTo>
        <relationshipLabel>UST Event Appointments</relationshipLabel>
        <relationshipName>UG_Visit_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <label>Event Registration</label>
        <referenceTo>UST_Event_Registration__c</referenceTo>
        <relationshipName>UG_Event_Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Visit/Event</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Not Planning to Attend</fullName>
                    <isActive>false</isActive>
                    <label>Not Planning to Attend</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Appointment_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Actuarial Science</fullName>
    </customValue>
    <customValue>
        <fullName>Art History</fullName>
    </customValue>
    <customValue>
        <fullName>Biochemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Biology of Global Health</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Family Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Financial Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- General Business Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Human Resource Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- International Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Leadership and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Legal Studies in Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Marketing Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Operations Management</fullName>
    </customValue>
    <customValue>
        <fullName>Busienss Administration- Real Estate Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Catholic Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Classical Civilization</fullName>
    </customValue>
    <customValue>
        <fullName>Classical Langauges</fullName>
    </customValue>
    <customValue>
        <fullName>Communication and Journalism</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Criminal Justice</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Education- Elementary</fullName>
    </customValue>
    <customValue>
        <fullName>Education- Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering- Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering- Biomedical</fullName>
    </customValue>
    <masterLabel>Appointment Type</masterLabel>
</GlobalValueSet>

src/classes/USTEventSubmitController.cls
/**
 * Created by dahl3702 on 5/1/2018.
 */

public with sharing class USTEventSubmitController {
    public USTEventShared USTShared = new USTEventShared();
    public String test { get; set; }
    public USTEventShared.USTEventInfo evtInfo { get; set; }
    public List<UST_Event_Appointment_Type__c> appts { get; set; }
    public List<UST_Event_Appointments__c> chosenAppts { get; set; }
    public String chosenFormatted { get; set; }
    public UST_Event__C eventPage { get; set; }

    public USTEventSubmitController() {
        test = '';
        //Get cookie or URL string variable
        evtInfo = USTShared.getUSTEventInfo();
        chosenFormatted = '';
        if(!String.isEmpty(evtInfo.evtId)) {
            eventPage = [SELECT Event_Submit_Title__c, Event_Submit_Description__c, Event_Footer__c, Template__c FROM UST_Event__c WHERE Id = :evtinfo.evtId][0];
        }

        if (!String.isBlank(evtinfo.evtRegId)) {
            chosenAppts = [SELECT Id, Appointment_Category__c, Event_Appointment_Type__c, Appointment_Type__c, Appointment_Title__c FROM UST_Event_Appointments__c WHERE Event_Registration__c = :evtinfo.evtRegId ORDER BY Appointment_Title__c];
            if (chosenAppts.size() > 0) {
                chosenFormatted += '<ul id="choosenAppointments">';
                for (UST_Event_appointments__c cappt : chosenAppts) {
                    chosenFormatted += '<li>';
                    chosenFormatted += cappt.Appointment_Title__c;
                    if (!String.isEmpty(cappt.Appointment_Type__c)) {
                        chosenFormatted += '<br/><em>' + cappt.Appointment_Type__c + '</em>';
                    }
                    chosenFormatted += '</li>';
                }
                chosenFormatted += '</ul>';
            }
        }

    }

    public PageReference submitRegistration () {
        //Change Status of registration to complete
        UST_Event_Registration__c evtReg = [SELECT Id, Status__c FROM UST_Event_Registration__c WHERE id = :evtInfo.evtRegId][0];
        evtReg.Status__c = 'Requested';
        upsert evtReg;
        PageReference confirmPage = Page.USTEventConfirmation;
        return confirmPage;
    }

    public PageReference previousPage() {
        List<UST_Event_Appointment_Type__c> apptTypes = [SELECT Id From UST_Event_Appointment_Type__c WHERE UST_Event__c = :evtInfo.evtId];
        PageReference lastPage;
        if (apptTypes.size() == 0) {
            //If no options skip that step
            lastPage = Page.USTEventRegister;
        } else {
            lastPage = Page.USTEventRegistrationOptions;
        }
        // create cookie to pass on to next page
        //Posting along everything we need to build the next page
        String encrytpString = USTShared.createEncryptedCookie('{"audience":"' + evtInfo.audience + '","sessionID":"' + evtInfo.sessionID + '","evtRegId":"' + evtInfo.evtRegId + '","evtId":"' + evtInfo.evtId + '"}', 'USTEvent');
        //String decryptCookie = cookieWork.getDecryptCookie('USTEvent');
        //lastPage.getParameters().put('evt', encrytpString);
        return lastPage;
    }
}