src/objects/UST_Event__c.object
<CustomObject>
    <description>Parent Event object to setup individual Event Sessions</description>
    <fields>
        <fullName>Event_Cancel_Review_Description__c</fullName>
        <description>The instructions on the cancel review page.</description>
        <inlineHelpText>The instructions on the cancel review page.</inlineHelpText>
        <label>Event Cancel Review Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Cancel_Review_Title__c</fullName>
        <description>The title on the page for cancel an review</description>
        <inlineHelpText>The title on the page for cancel an review</inlineHelpText>
        <label>Event Cancel Review Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Cancelled_Notification_Text__c</fullName>
        <description>The text that appears to tell a client that their event is cancelled on the review cancel page.</description>
        <inlineHelpText>The text that appears to tell a client that their event is cancelled on the review cancel page.</inlineHelpText>
        <label>Event Cancelled Notification Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Footer__c</fullName>
        <description>Footer that follows through event process. Can contain contact information for issues and information</description>
        <inlineHelpText>Footer that follows through event process. Can contain contact information for issues and information</inlineHelpText>
        <label>Event Footer</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Home_Link_Title__c</fullName>
        <defaultValue>&apos;Event Home&apos;</defaultValue>
        <description>The title that will appear as a link at the top of the page to take you back to wherever you described the event on the Web.</description>
        <inlineHelpText>The title that will appear as a link at the top of the page to take you back to wherever you described the event on the Web.</inlineHelpText>
        <label>Event Home Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Home_Link_URL__c</fullName>
        <description>The link to the page that initiated the event registration.</description>
        <inlineHelpText>The link to the page that initiated the event registration.</inlineHelpText>
        <label>Event Home Link URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_description__c</fullName>
        <description>Description of Event</description>
        <inlineHelpText>Describe the event</inlineHelpText>
        <label>Event Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <defaultValue>&apos;CastorTemplate2017&apos;</defaultValue>
        <description>Chose a pre-programmed template for your event site</description>
        <inlineHelpText>Chose a pre-programmed template for your event site</inlineHelpText>
        <label>Template</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CastorTemplate2017</fullName>
                </value>
                <value>
                    <fullName>OPUSTemplate2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event</label>
    <nameField>
        <label>Event Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UST Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <fields>
        <fullName>Appointment_Category__c</fullName>
        <label>Appointment Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Appointment_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Appointment_Title__c</fullName>
        <description>Display title of appointment</description>
        <inlineHelpText>Display title of appointment</inlineHelpText>
        <label>Appointment Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Appointment_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Appointment_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <label>Event Registration</label>
        <referenceTo>UST_Event_Registration__c</referenceTo>
        <relationshipName>UG_Event_Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>UG_Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Visit/Event</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Received</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rescheduled</fullName>
                </value>
                <value>
                    <fullName>Status</fullName>
                </value>
                <value>
                    <fullName>Not Planning to Attend</fullName>
                    <isActive>false</isActive>
                    <label>Not Planning to Attend</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Appointment_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Actuarial Science</fullName>
    </customValue>
    <customValue>
        <fullName>Art History</fullName>
    </customValue>
    <customValue>
        <fullName>Biochemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Biology of Global Health</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Family Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Financial Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- General Business Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Human Resource Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- International Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Leadership and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Legal Studies in Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Marketing Management</fullName>
    </customValue>
    <customValue>
        <fullName>Business Administration- Operations Management</fullName>
    </customValue>
    <customValue>
        <fullName>Busienss Administration- Real Estate Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Catholic Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Chemistry</fullName>
    </customValue>
    <customValue>
        <fullName>Classical Civilization</fullName>
    </customValue>
    <customValue>
        <fullName>Classical Langauges</fullName>
    </customValue>
    <customValue>
        <fullName>Communication and Journalism</fullName>
    </customValue>
    <customValue>
        <fullName>Computer Science</fullName>
    </customValue>
    <customValue>
        <fullName>Criminal Justice</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Education- Elementary</fullName>
    </customValue>
    <customValue>
        <fullName>Education- Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering- Aerospace</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering- Biomedical</fullName>
    </customValue>
    <masterLabel>Appointment Type</masterLabel>
</GlobalValueSet>

src/classes/USTEventCancelReviewController.cls
/**
 * Created by dahl3702 on 5/1/2018.
 */

public with sharing class USTEventCancelReviewController {
    public USTEventShared USTShared = new USTEventShared();
    public String outString {get;set;}
    public UST_Event_Registration__c evt {get;set;}
    public List<UST_Event_Appointments__c> appt {get;set;}
    public String eventDesc {get;set;}
    public String templateSelected { get; set; }

    public USTEventCancelReviewController() {
        templateSelected =  USTShared.defaultTemplate;
        String regId = ApexPages.currentPage().getParameters().get('regId');

        if (!String.isBlank(regId)) {
            evt = [SELECT id, Status__c, Name, Event__r.Name, Event__r.Event_description__c,
                    Event__r.Event_Footer__c, Event__r.Event_Cancel_Review_Title__c,
                    Event__r.Event_Cancel_Review_Description__c, Event__r.Event_Cancelled_Notification_Text__c,
                    Event__r.Template__c, Event__r.Event_Home_Link_Title__c, Event__r.Event_Home_Link_URL__c
            FROM UST_Event_Registration__c WHERE id = :regId][0];
            
            templateSelected = evt.Event__r.Template__c;

            if (evt != null) {
                appt = [SELECT Id, Appointment_Title__c, Appointment_Category__c, Appointment_Type__c FROM UST_Event_Appointments__c WHERE Event_Registration__c = :regId];
            }
        }
    }


    public PageReference cancelRegistration() {
        if (evt != null) {
            evt.Status__c = 'Cancelled';
            upsert evt;
        }
        pageReference pg = new pageReference(ApexPages.currentPage().getURL());
        pg.getParameters().put('regid',evt.id);
        pg.setRedirect(TRUE);
        return pg;
    }

}