src/objects/UST_Event__c.object
<CustomObject>
    <description>Parent Event object to setup individual Event Sessions</description>
    <fields>
        <fullName>Event_Confirmation_Description__c</fullName>
        <description>The final page of the event registration. Thank for the registration and describe next steps.</description>
        <inlineHelpText>The final page of the event registration. Thank for the registration and describe next steps.</inlineHelpText>
        <label>Event Confirmation Description</label>
        <length>15000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Event_Confirmation_Title__c</fullName>
        <description>The title that appears on the confirmation page of the event process</description>
        <inlineHelpText>The title that appears on the confirmation page of the event process</inlineHelpText>
        <label>Event Confirmation Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Footer__c</fullName>
        <description>Footer that follows through event process. Can contain contact information for issues and information</description>
        <inlineHelpText>Footer that follows through event process. Can contain contact information for issues and information</inlineHelpText>
        <label>Event Footer</label>
        <length>3000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <defaultValue>&apos;CastorTemplate2017&apos;</defaultValue>
        <description>Chose a pre-programmed template for your event site</description>
        <inlineHelpText>Chose a pre-programmed template for your event site</inlineHelpText>
        <label>Template</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CastorTemplate2017</fullName>
                </value>
                <value>
                    <fullName>OPUSTemplate2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event</label>
    <nameField>
        <label>Event Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UST Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointment_Type__c.object
<CustomObject>
    <description>List of available appointments for a session</description>
    <fields>
        <fullName>UST_Event__c</fullName>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Appointment Types</relationshipLabel>
        <relationshipName>UG_Event_Appointment_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment Type</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>UG Event Appointment Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointment Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/USTEventConfirmationController.cls
/**
 * Created by dahl3702 on 5/1/2018.
 */

public with sharing class USTEventConfirmationController {
    public USTEventShared USTShared = new USTEventShared();
    public String test { get; set; }
    public USTEventShared.USTEventInfo evtInfo { get; set; }
    public List<UST_Event_Appointment_Type__c> appts { get; set; }
    public List<UST_Event_Appointments__c> chosenAppts { get; set; }
    public String chosenFormatted { get; set; }
    public UST_Event__C eventPage { get; set; }


    public USTEventConfirmationController() {
        evtInfo = USTShared.getUSTEventInfo();
        if (!String.isEmpty(evtInfo.evtId)) {
            eventPage = [SELECT Event_Confirmation_Title__c, Template__c, Event_Confirmation_Description__c, Event_Footer__c FROM UST_Event__c WHERE Id = :evtinfo.evtId][0];
        }
        //Delete cookie
        Cookie deleteCookie = new Cookie('USTEvent', '', null, 0, false); // Note the 0 to delete the cookie
        ApexPages.currentPage().setCookies(new Cookie[]{
                deleteCookie
        });
    }

}