src/objects/UST_Event__c.object
<CustomObject>
    <description>Parent Event object to setup individual Event Sessions</description>
    <fields>
        <fullName>Allow_Other_Attendees__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activate allowing other attendees to the event in addition to primary attendee</description>
        <inlineHelpText>Activate allowing other attendees to the event in addition to primary attendee</inlineHelpText>
        <label>Allow Other Attendees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ask_Gender__c</fullName>
        <description>Ask about a registrants gender</description>
        <inlineHelpText>Ask about a registrants gender</inlineHelpText>
        <label>Ask Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Do not ask</fullName>
                </value>
                <value>
                    <fullName>Ask but do not require</fullName>
                </value>
                <value>
                    <fullName>Ask and require</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Audience__c</fullName>
        <description>Choose the audience that this event is targeted.</description>
        <inlineHelpText>Choose the audience that this event is targeted.</inlineHelpText>
        <label>Audience</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High School Senior</fullName>
                </value>
                <value>
                    <fullName>High School Junior or Younger</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>First-Year International</fullName>
                </value>
                <value>
                    <fullName>Transfer International</fullName>
                </value>
                <value>
                    <fullName>Graduate Student</fullName>
                </value>
                <value>
                    <fullName>International Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Prospective Graduate Student</fullName>
                </value>
                <value>
                    <fullName>Graduate Alumni</fullName>
                </value>
                <value>
                    <fullName>Graduate Public</fullName>
                </value>
                <value>
                    <fullName>Graduate Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Close_Event_Days_Before__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of days before the event that you want registration to close (accepting no new registrants)</description>
        <inlineHelpText>The amount of days before the event that you want registration to close (accepting no new registrants)</inlineHelpText>
        <label>Close Event Days Before</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>College_High_School_Ask__c</fullName>
        <description>Get High School and College information and last attended/graduation date.</description>
        <inlineHelpText>Get High School and College information and last attended/graduation date.</inlineHelpText>
        <label>College High School Ask</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Don&apos;t ask</fullName>
                </value>
                <value>
                    <fullName>Both College and HS</fullName>
                </value>
                <value>
                    <fullName>HS Only</fullName>
                </value>
                <value>
                    <fullName>College Only</fullName>
                </value>
                <value>
                    <fullName>Auto Select on Audience</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Date event ends</description>
        <inlineHelpText>Date event ends</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Home_Link_Title__c</fullName>
        <defaultValue>&apos;Event Home&apos;</defaultValue>
        <description>The title that will appear as a link at the top of the page to take you back to wherever you described the event on the Web.</description>
        <inlineHelpText>The title that will appear as a link at the top of the page to take you back to wherever you described the event on the Web.</inlineHelpText>
        <label>Event Home Link Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Home_Link_URL__c</fullName>
        <description>The link to the page that initiated the event registration.</description>
        <inlineHelpText>The link to the page that initiated the event registration.</inlineHelpText>
        <label>Event Home Link URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Event Name</description>
        <inlineHelpText>Name of the event</inlineHelpText>
        <label>Event Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <description>Status of event (Planning, Active, Inactive, Closed, Cancelled)</description>
        <inlineHelpText>Status of event (Planning, Active, Inactive, Closed, Cancelled)</inlineHelpText>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Active_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Include_Time_frame_List__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Ask the client for a general time-frame for event (drop down)</description>
        <inlineHelpText>Ask the client for a general time-frame for event (drop down)</inlineHelpText>
        <label>Include Time frame List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Other_Attendees__c</fullName>
        <description>If other attendees is active, how many other attendees are allowed to this event</description>
        <inlineHelpText>If other attendees is active, how many other attendees are allowed to this event</inlineHelpText>
        <label>Max Other Attendees</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the event begins</description>
        <inlineHelpText>Date the event begins</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <defaultValue>&apos;CastorTemplate2017&apos;</defaultValue>
        <description>Chose a pre-programmed template for your event site</description>
        <inlineHelpText>Chose a pre-programmed template for your event site</inlineHelpText>
        <label>Template</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CastorTemplate2017</fullName>
                </value>
                <value>
                    <fullName>OPUSTemplate2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>UST Event</label>
    <nameField>
        <label>Event Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UST Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointment_Type__c.object
<CustomObject>
    <description>List of available appointments for a session</description>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title of appointment in 255 characters or less</description>
        <inlineHelpText>Title of appointment in 255 characters or less</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UST_Event__c</fullName>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Appointment Types</relationshipLabel>
        <relationshipName>UG_Event_Appointment_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment Type</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>UG Event Appointment Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointment Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <fields>
        <fullName>Event_Appointment_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Thad Appointment Definition</inlineHelpText>
        <label>Event Appointment Type</label>
        <referenceTo>UST_Event_Appointment_Type__c</referenceTo>
        <relationshipLabel>UST Event Appointments</relationshipLabel>
        <relationshipName>UG_Visit_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <label>Event Registration</label>
        <referenceTo>UST_Event_Registration__c</referenceTo>
        <relationshipName>UG_Event_Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Instance__c.object
<CustomObject>
    <description>Individual Event occurrence for Event Registrations</description>
    <fields>
        <fullName>Active_Status__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <label>Active Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Active_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Capacity of the Event Session</description>
        <inlineHelpText>Capacity of this Event Session</inlineHelpText>
        <label>Capacity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Available_Capacity__c</fullName>
        <formula>Capacity__c - Count_of_Attendees__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Available Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <formula>Event__r.Event_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Instances</relationshipLabel>
        <relationshipName>Event_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>UST Event Instance</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Event Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Instance__c</fullName>
        <label>Event Instance</label>
        <referenceTo>UST_Event_Instance__c</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <formula>Event_Instance__r.Event_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>UG_Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUSTEventShared.cls
/**
 * Created by dahl3702 on 6/12/2018.
 */

@isTest
public with sharing class TestUSTEventShared {
    @testSetup static void insertCertainBaselineDataForTestsIfNotPresent() {
        Util.insertCertainBaselineDataForTestsIfNotPresent();
    }
    private static USTEventShared USTShared = new USTEventShared();
    private static USTEventCancelReviewController cancelReviewCtrl;
    private static USTEventConfirmationController confirmCtrl;
    private static USTEventParkingPassController parkingCtrl;
    private static USTEventRegisterController registerCtrl;
    private static USTEventRegistrationOptionsController optionsCtrl;
    private static USTEventSubmitController submitCtrl;
    private static UST_Event__c testEvent;
    private static UST_Event_Appointment_Type__c testAppointmentTypes;
    private static UST_Event_Appointment_Type__c testAppointmentTypes2;
    private static UST_Event_Instance__c testInstance;
    private static UST_Event_Registration__c testRegistration;
    private static UST_Event_Appointments__c testAppointments;
    private static UST_Event_Appointments__c testAppointments2;
    private static User testUser;
    private static Contact student;
    private static String audience { get; set; }
    private static String template { get; set; }

    static testMethod void testRegister() {

        Test.startTest();

        //Making bad cookies for exceptions
        String eventForCookie = '{"blah":"blah"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        USTShared.getUSTEventInfo();

        registerCtrl = new USTEventRegisterController();

        createEventWithRegistration('email');
        eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.id + '","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        registerCtrl = new USTEventRegisterController();
        registerCtrl.saveContactRegistration();

        createEventWithRegistration('lastzip');
        eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.id + '","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        registerCtrl = new USTEventRegisterController();
        registerCtrl.saveContactRegistration();

        // THANKS EnrollmentRx for making this query max out the queries for this test. Now I can only get 91.72% coverage
        //        createEventWithRegistration('none');
        //        eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.id + '","evtId":"' + testEvent.Id + '"}';
        //        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        //        registerCtrl = new USTEventRegisterController();
        //        registerCtrl.saveContactRegistration();

        createEventWithRegistration('');
        eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"COMING","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        registerCtrl = new USTEventRegisterController();
        registerCtrl.saveContactRegistration();

        //Log in as portal user
        System.runAs(testUser) {
            eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"COMING","evtId":"' + testEvent.Id + '"}';
            USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
            registerCtrl = new USTEventRegisterController();

            //Use audience Transfer to set college for school
            eventForCookie = '{"audience":"Transfer","instanceID":"' + testInstance.Id + '","evtRegId":"COMING","evtId":"' + testEvent.Id + '"}';
            USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
            registerCtrl = new USTEventRegisterController();

            //Create event with registraiton ID
            eventForCookie = '{"audience":"Transfer","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.id + '","evtId":"' + testEvent.Id + '"}';
            USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
            registerCtrl = new USTEventRegisterController();
            registerCtrl.checkEventDetails();
            registerCtrl.getSexDD();
            registerCtrl.getStateDD();
            registerCtrl.getTimeFrame();
            registerCtrl.saveContactRegistration();
        }

        //Submit the registration
        submitCtrl = new USTEventSubmitController();
        submitCtrl.checkEventDetails();
        submitCtrl.previousPage();
        submitCtrl.submitRegistration();

        delete testAppointments;
        delete testAppointments2;
        update testRegistration;
        submitCtrl.submitRegistration();
    }

    static testMethod void testOptions() {
        Test.startTest();
        optionsCtrl = new USTEventRegistrationOptionsController();

        createEventWithRegistration('');
        String eventForCookie = '{"audience":"Transfer","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.Id + '","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        optionsCtrl = new USTEventRegistrationOptionsController();

        optionsCtrl.checkEventDetails();
        optionsCtrl.previousPage();

        optionsCtrl.incomingApptJSon = '[]';
        optionsCtrl.saveOptions();

        //[{"apptId":"a010m000003EibeAAC","apptCatagory":"","apptType":"","apptText":"","apptTitle":"Multi colored socks for everyone"},{"apptId":"a010m000003EibUAAS","apptCatagory":"","apptType":"","apptText":"","apptTitle":"Red Socks Only"}]
        optionsCtrl.incomingApptJSon = '[{"apptId":"' + testAppointmentTypes.Id + '","apptCatagory":"","apptType":"","apptText":"","apptTitle":"' + testAppointmentTypes.Title__c + '"}]';
        optionsCtrl.saveOptions();

        //run constructor again to simulate page load after save
        testRegistration.UG_Event_Appointments__r.add(testAppointments2);
        optionsCtrl = new USTEventRegistrationOptionsController();
    }


    static testMethod void testCancel() {
        createEventWithRegistration('');
        Test.startTest();
        PageReference pageRef = Page.USTEventCancelReview;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('regId', testRegistration.Id);
        cancelReviewCtrl = new USTEventCancelReviewController();
        cancelReviewCtrl.cancelRegistration();
    }

    static testMethod void testConfirmation() {
        createEventWithRegistration('');
        Test.startTest();
        //{"audience":"High School Senior","instanceID":"a320m000000A5fOAAS","evtRegId":"a350m0000008q63AAA","evtId":"a330m0000001SOrAAM"}
        String eventForCookie = '{"audience":"' + audience + '","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.Id + '","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        confirmCtrl = new USTEventConfirmationController();
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        confirmCtrl.checkEventDetails();
    }

    static testMethod void testParkingPass() {
        createEventWithRegistration('');
        Test.startTest();
        parkingCtrl = new USTEventParkingPassController();
        ApexPages.currentPage().getParameters().put('regId', testRegistration.Id);
        parkingCtrl = new USTEventParkingPassController();
        testRegistration.Date__c = testInstance.Start_Date_Time__c.date();
        upsert testRegistration;
        parkingCtrl = new USTEventParkingPassController();
    }

    static testMethod void testFeed() {
        createTestEvent();
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/applicantportal/services/apexrest/usteventfeed';
        req.httpMethod = 'GET';
        req.addHeader('Content-Type', 'application/json');

        //Test audience dd request
        req.params.put('feedType', 'audienceDD');
        RestContext.request = req;
        RestContext.response = res;
        USTEventFeed.getUSTEventFeed();

        //Test sex dd request
        req.params.remove('feedType');
        req.params.put('feedType', 'sexDD');
        RestContext.request = req;
        USTEventFeed.getUSTEventFeed();

        //test filter minus dates
        req.params.remove('feedType');
        req.params.put('feedType', 'eventList');
        RestContext.request = req;
        USTEventFeed.getUSTEventFeed();

        //test filter with start date
        req.params.put('viewStart', String.valueOf(Datetime.now().addMonths(-1)));
        RestContext.request = req;
        USTEventFeed.getUSTEventFeed();

        //test filter with end date
        req.params.put('viewEnd', String.valueOf(Datetime.now().addMonths(1)));
        req.params.put('audience', audience);
        RestContext.request = req;
        USTEventFeed.getUSTEventFeed();
    }

    static testMethod void testUSTEventShared() {
        // USTShared = new USTEventShared();
        createEventWithRegistration('');
        String eventForCookie = '{"audience":"Transfer","instanceID":"' + testInstance.Id + '","evtRegId":"' + testRegistration.Id + '","evtId":"' + testEvent.Id + '"}';
        USTShared.createEncryptedCookie(eventForCookie, 'USTEvent');
        ApexPages.currentPage().getParameters().put('instanceID', '000000000000000');
        USTShared.getUSTEventInfo();
        //dataPrepare();
        //Test.startTest();
        //String TestEncryptedCookie = USTShared.createEncryptedCookie('{"audience":"' + mainEvent.Audience__c + '","instanceID":"' + mainInstance.Id + '","evtRegId":"'+ma+'","evtId":"a330m0000001SOrAAM"}');
    }


//    WHERE Start_Date_Time__c >= :viewStart
//    AND Event__R.Event_Status__c = 'Active'
//    AND Active_Status__c = 'Active'
//    AND Start_Date_Time__c <= :viewEnd
//    AND (Current_Available_Capacity__c > 0 OR Capacity__c = null)
//            AND Event__r.Audience__c INCLUDES(:audience)

    private static void createTestEvent() {
        audience = pickOneOnPicklist(UST_Event__c.Audience__c.getDescribe());
        template = pickOneOnPicklist(UST_Event__C.Template__c.getDescribe());
        //Create event
        testEvent = new UST_Event__c(
                Name = 'Test Event',
                Event_Status__c = 'Active',
                Event_Name__c = 'Test Event',
                Start_Date__c = Date.today().addDays(1),
                End_Date__c = Date.today().addDays(1),
                Template__c = template,
                Event_Home_Link_Title__c = 'testHome',
                Event_Home_Link_URL__c = '/',
                College_High_School_Ask__c = 'Auto Select on Audience',
                Ask_Gender__c = 'Ask and require',
                Include_Time_frame_List__c = true,
                Allow_Other_Attendees__c = true,
                Max_Other_Attendees__c = 5,
                Close_Event_Days_Before__c = 0,
                Audience__c = audience);
        insert testEvent;
        //Create appointment  types
        testAppointmentTypes = new UST_Event_Appointment_Type__c(
                UST_Event__c = testEvent.Id,
                Title__c = 'Test Appointment',
                Appointment_Limits__c = '1',
                Description__c = 'Test description'
        );
        insert testAppointmentTypes;

        String apptCategory = pickOneOnPicklist(UST_Event_Appointment_Type__c.Appointment_Category__c.getDescribe());
        testAppointmentTypes2 = new UST_Event_Appointment_Type__c(
                UST_Event__c = testEvent.Id,
                Title__c = 'Test Appointment',
                Appointment_Limits__c = '1',
                Description__c = 'Test description',
                Appointment_Category__c = apptCategory
        );
        insert testAppointmentTypes2;


        //Create event instance
        testInstance = new UST_Event_Instance__c(
                Event__c = testEvent.Id,
                Instance_Title__c = 'Test Sesssion',
                Start_Date_Time__c = Datetime.now().addDays(1),
                End_Date_Time__c = Datetime.now().addDays(1).addHours(5),
                Active_Status__c = 'Active',
                Capacity__c = 500
        );
        insert testInstance;
    }

    private static void createEventWithRegistration(String contactType) {
        if (testEvent == null) {
            createTestEvent();
        }
        if (testUser == null) {
            creatTestUser();
        }
        if (contactType == 'lastzip') {
            testRegistration = new UST_Event_Registration__c(
                    Event__c = testEvent.Id,
                    Event_Instance__c = testInstance.Id,
                    Registrant_Email__c = 'notamatch@valleyhill.net',
                    Registrant_First_Name__c = student.firstName,
                    Registrant_Last_Name__c = student.lastname,
                    Registrant_Zip__c = student.mailingpostalcode,
                    Registrant_High_School_Code__c = '000000'
            );
        } else if (contactType == 'email') {
            testRegistration = new UST_Event_Registration__c(
                    Event__c = testEvent.Id,
                    Event_Instance__c = testInstance.Id,
                    Registrant_Email__c = student.email,
                    Registrant_First_Name__c = student.firstname,
                    Registrant_Last_Name__c = 'NotaMatch',
                    Registrant_Zip__c = '00000',
                    Registrant_High_School_Code__c = '000000',
                    Registrant_College_Code__c = '000000'
            );
        } else if (contactType == 'none') {
            testRegistration = new UST_Event_Registration__c(
                    Event__c = testEvent.Id,
                    Event_Instance__c = testInstance.Id,
                    Registrant_Email__c = 'none@valleyhill.net',
                    Registrant_First_Name__c = 'None',
                    Registrant_Last_Name__c = 'Canmatch',
                    Registrant_Zip__c = '55413',
                    Registrant_College_Code__c = '000000'
            );
        } else {
            testRegistration = new UST_Event_Registration__c(
                    Event__c = testEvent.Id,
                    Event_Instance__c = testInstance.Id,
                    Registrant_Email__c = student.email,
                    Registrant_First_Name__c = student.firstname,
                    Registrant_Last_Name__c = student.lastname,
                    Registrant_Zip__c = student.mailingpostalcode,
                    Registrant_College_Code__c = '000000'
            );
        }
        insert testRegistration;

        if (String.isBlank(contactType)) {
            testAppointments = new UST_Event_Appointments__c(
                    Event_Registration__c = testRegistration.Id,
                    Event_Appointment_Type__c = testAppointmentTypes.Id,
                    Client_Created_Appointment__c = true
            );
            insert testAppointments;
            testAppointments2 = new UST_Event_Appointments__c(
                    Event_Registration__c = testRegistration.Id,
                    Event_Appointment_Type__c = testAppointmentTypes2.Id,
                    Client_Created_Appointment__c = true
            );
            insert testAppointments2;
        }


    }

    private static void creatTestUser() {
        //Querying on profile


        //Creating a student contact
        student = new Contact(
                firstName = 'Freddy',
                lastName = 'McFlintstone',
                Email = 'fredmcflintsone@valleyhill.net',
                MailingStreet = '123 Flinstone Ave',
                MailingCity = 'Bedrock',
                MailingState = 'MN',
                MailingPostalCode = '55418',
                MailingZip__c = '55418',
                MailingCountry = 'US',
                Receive_Texts__c = 'Yes'
        );
        insert student;

        //Creating a test user based on the student
        Profile testProfile = [select id, name from profile where name = 'Student Portal User'][0];
        System.Debug('PROFILE ID: ' + testProfile.Id);
        testUser = new User(
                firstName = student.firstName,
                lastName = student.lastName,
                email = student.email,
                username = student.email,
                alias = 'eTester',
                ProfileId = testProfile.Id,
                contactId = student.Id,
                TimeZoneSidKey = 'America/Chicago',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US'
        );
        insert testUser;
    }

    private static String pickOneOnPicklist(Schema.DescribeFieldResult fieldResult) {
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        if (ple.size() > 0) {
            return ple[0].getValue();
        }
        return '';
    }
}