src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Buildings</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <formula>Event_Registration__r.Contact__r.FirstName &amp;&quot; &quot;&amp; Event_Registration__r.Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Host__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the host assigned to for this appointment.</description>
        <inlineHelpText>Link to the host assigned to for this appointment.</inlineHelpText>
        <label>Event Host</label>
        <referenceTo>UST_Event_Host__c</referenceTo>
        <relationshipLabel>UST Event Appointments</relationshipLabel>
        <relationshipName>UST_Event_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <label>Event Registration</label>
        <referenceTo>UST_Event_Registration__c</referenceTo>
        <relationshipName>UG_Event_Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Host__c.object
<CustomObject>
    <description>Hosts that can be applied to appointments on an event registration record.</description>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>Additional comments about the host that will appear in any generated itinerary.</description>
        <inlineHelpText>Additional comments about the host that will appear in any generated itinerary.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Assigned__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of registrants currently assigned to this host.</description>
        <inlineHelpText>The number of registrants currently assigned to this host.</inlineHelpText>
        <label>Assigned</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <description>The building where the hosting will be happening.</description>
        <inlineHelpText>The building where the hosting will be happening.</inlineHelpText>
        <label>Building</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Buildings</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact record in Salesforce for this host.</description>
        <inlineHelpText>The contact record in Salesforce for this host.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>UST Event Hosts</relationshipLabel>
        <relationshipName>UST_Event_Hosts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Name of the hosting course (if it is a course).</description>
        <inlineHelpText>Name of the hosting course (if it is a course).</inlineHelpText>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>The department a faculty or staff host works.</description>
        <inlineHelpText>The department a faculty or staff host works.</inlineHelpText>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Instance__c</fullName>
        <description>Event Instance in which hosts can be applied</description>
        <inlineHelpText>Event Instance in which hosts can be applied</inlineHelpText>
        <label>UST Event Instance</label>
        <referenceTo>UST_Event_Instance__c</referenceTo>
        <relationshipLabel>UST Event Hosts</relationshipLabel>
        <relationshipName>UST_Event_Hosts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the host.</description>
        <inlineHelpText>First name of the host.</inlineHelpText>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formatted_Time__c</fullName>
        <formula>TEXT( 
IF((HOUR(Time__c) &gt; 12), 
HOUR(Time__c) - 12, 
IF(HOUR(Time__c) == 0, 12, HOUR(Time__c)) 
) 

) 
&amp; 
IF(!ISBLANK(HOUR(Time__c)),&apos;:&apos;,&apos;&apos;) 
&amp; 
IF(MINUTE(Time__c)&lt;10,&apos;0&apos;,&apos;&apos;) 
&amp; 
TEXT( 
MINUTE(Time__c) 
) 
&amp; 
IF(!ISBLANK(MINUTE(Time__c)),&apos; &apos;,&apos;&apos;) 
&amp; 
IF(!ISBLANK(HOUR(Time__c)), 
IF(HOUR(Time__c) &gt;= 12, &apos;PM&apos;, &apos;AM&apos;), &apos;&apos; 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Formatted Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the host (important for overnight hosting).</description>
        <inlineHelpText>Gender of the host (important for overnight hosting).</inlineHelpText>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the host</description>
        <inlineHelpText>Last name of the host</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Room and building number, address, where hosting will be happening.</description>
        <inlineHelpText>Room and building number, address, where hosting will be happening.</inlineHelpText>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Title__c</fullName>
        <description>The preferred title of the host (Professor, Dr., Burgermeister Meisterburger).</description>
        <inlineHelpText>The preferred title of the host (Professor, Dr., Burgermeister Meisterburger).</inlineHelpText>
        <label>Preferred Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining__c</fullName>
        <description>The remaining amount of spaces left in the max capacity of registrants a host can take.</description>
        <formula>Max_Available__c -  Assigned__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The remaining amount of spaces left in the max capacity of registrants a host can take.</inlineHelpText>
        <label>Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Undergrad_Major__c</fullName>
        <description>The major the host is pursuing at St. Thomas.</description>
        <inlineHelpText>The major the host is pursuing at St. Thomas.</inlineHelpText>
        <label>Undergrad Major</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Academic_Majors</valueSetName>
        </valueSet>
    </fields>
    <label>UST Event Host</label>
    <nameField>
        <displayFormat>HOST-{0000}</displayFormat>
        <label>UST Event Host Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Hosts</pluralLabel>
    <recordTypes>
        <fullName>Class</fullName>
        <active>true</active>
        <description>Visit a class</description>
        <label>Class</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Instance__c.object
<CustomObject>
    <description>Individual Event occurrence for Event Registrations</description>
    <label>UST Event Instance</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Event Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>UST_Event_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Instance__c</fullName>
        <label>Event Instance</label>
        <referenceTo>UST_Event_Instance__c</referenceTo>
        <relationshipLabel>UST Event Registrations</relationshipLabel>
        <relationshipName>Event_Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Buildings.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>2085/87 Grand Avenue (SJV Grand) (85G)</fullName>
    </customValue>
    <customValue>
        <fullName>2109 Grand Avenue (09G)</fullName>
    </customValue>
    <customValue>
        <fullName>2151 Grand Avenue (51G)</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Athletic &amp; Recreation Complex (ARC)</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson Student Center (ASC)</fullName>
    </customValue>
    <customValue>
        <fullName>Aquinas Hall (AQU)</fullName>
    </customValue>
    <customValue>
        <fullName>Archbishop Ireland Memorial Library (IRL)</fullName>
    </customValue>
    <customValue>
        <fullName>Art History (44C)</fullName>
    </customValue>
    <customValue>
        <fullName>Binz Refectory (BIN)</fullName>
    </customValue>
    <customValue>
        <fullName>Brady Educational Center (BEC)</fullName>
    </customValue>
    <customValue>
        <fullName>Brady Hall (BRA)</fullName>
    </customValue>
    <customValue>
        <fullName>CDC Student Residence (CDC)</fullName>
    </customValue>
    <customValue>
        <fullName>Chapel of St. Thomas Aquinas (CHA)</fullName>
    </customValue>
    <customValue>
        <fullName>Child Development Center (CDC)</fullName>
    </customValue>
    <customValue>
        <fullName>Cretin Hall (CRE)</fullName>
    </customValue>
    <customValue>
        <fullName>Dowling Hall (DOW)</fullName>
    </customValue>
    <customValue>
        <fullName>Facilities &amp; Design Center (FDC)</fullName>
    </customValue>
    <customValue>
        <fullName>Flynn Hall (FRH)</fullName>
    </customValue>
    <customValue>
        <fullName>Grace Hall (GRA)</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland Hall (IRE)</fullName>
    </customValue>
    <customValue>
        <fullName>John P. Monahan Plaza</fullName>
    </customValue>
    <customValue>
        <fullName>John Paul II Hall (JP2)</fullName>
    </customValue>
    <customValue>
        <fullName>John R Roach Center for Liberal Arts (JRC)</fullName>
    </customValue>
    <customValue>
        <fullName>Koch Commons (KOC)</fullName>
    </customValue>
    <customValue>
        <fullName>Loras Hall (LOR)</fullName>
    </customValue>
    <customValue>
        <fullName>McCarthy Gym, (MCG)</fullName>
    </customValue>
    <customValue>
        <fullName>McNeely Hall (MCH)</fullName>
    </customValue>
    <customValue>
        <fullName>Minneapolis Campus Buildings</fullName>
    </customValue>
    <customValue>
        <fullName>Morrison Hall (MOR)</fullName>
    </customValue>
    <customValue>
        <fullName>Murray Hall (MHC)</fullName>
    </customValue>
    <masterLabel>Buildings</masterLabel>
</GlobalValueSet>

src/classes/USTEventHostAssignementExtension.cls
/**
 * Created by dahl3702 on 10/30/2018.
 */

public with sharing class USTEventHostAssignementExtension {
    public UST_Event_Appointments__c USTApt;
    public Id instanceID {get;set;}
    public List<UST_Event_Host__c> listHost {get;set;}
    public Id hostId {get;set;}

    public USTEventHostAssignementExtension(ApexPages.StandardController stdController) {
        USTApt = (UST_Event_Appointments__c) stdController.getRecord();
        instanceID = USTApt.Event_Registration__r.Event_Instance__r.Id;
        listHost = [SELECT Name, Host_Type__c, Last_Name__c, First_Name__c, Preferred_Title__c,
                Gender__c, Undergrad_Major__c, Department__c, Contact__c,  Formatted_Time__c,
                Course_Name__c, Building__c, Location__c, Additional_Comments__c, Remaining__c,
                Assigned__c
        From UST_Event_Host__c
        WHERE Event_Instance__c = :instanceID];
    }

    public PageReference assignHost() {
        USTApt.Event_Host__c = hostId;
        upsert USTApt;
        return null;
    }
}