src/objects/UST_Event__c.object
<CustomObject>
    <description>Parent Event object to setup individual Event Sessions</description>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>Event Name</description>
        <inlineHelpText>Name of the event</inlineHelpText>
        <label>Event Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Short_Listing_Description__c</fullName>
        <description>This description displays on concise list of events and should not be verbose</description>
        <inlineHelpText>This description displays on concise list of events and should not be verbose</inlineHelpText>
        <label>Event Short Listing Description</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_description__c</fullName>
        <description>Description of Event</description>
        <inlineHelpText>Describe the event</inlineHelpText>
        <label>Event Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Location_Title__c</fullName>
        <description>Title of the location the event is taking place.</description>
        <inlineHelpText>Title of the location the event is taking place.</inlineHelpText>
        <label>Location Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>UST Event</label>
    <nameField>
        <label>Event Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UST Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UST_Event_Instance__c.object
<CustomObject>
    <description>Individual Event occurrence for Event Registrations</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <formula>Event__r.Event_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>UST_Event__c</referenceTo>
        <relationshipLabel>UST Event Instances</relationshipLabel>
        <relationshipName>Event_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Instance_Short_Description__c</fullName>
        <description>Short qualifying description of session.</description>
        <inlineHelpText>Short qualifying description of session.</inlineHelpText>
        <label>Instance Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_Title__c</fullName>
        <description>The title of the session under the event.</description>
        <inlineHelpText>The title of the session under the event.</inlineHelpText>
        <label>Instance Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Title_Override__c</fullName>
        <description>Overrides the master event configuration for title of the location the event is taking place.</description>
        <inlineHelpText>Overrides the master event configuration for title of the location the event is taking place.</inlineHelpText>
        <label>Location Title Override</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>UST Event Instance</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Event Instance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/USTEventAddToCalendarController.cls
/**
 * Created by dahl3702 on 11/12/2018.
 */

public with sharing class USTEventAddToCalendarController {

    public List<UST_Event_Instance__c> evtInfo { get; set; }
    public String DTSTART { get; set; }
    public String DTEND { get; set; }
    public String DTSTAMP { get; set; }
    public String TIMEZONE {get;set;}
    public String LOCATION { get; set; }
    public String DESCRIPTION { get; set; }
    public String LONGDESCRIPTION { get; set; }
    public String UUID { get; set; }

    public USTEventAddToCalendarController() {
        DTSTART = '';
        DTEND = '';
        DTSTAMP = '';
        LOCATION = '';
        DESCRIPTION = '';
        LONGDESCRIPTION = '';
        TIMEZONE = 'Central Daylight Time (America/Chicago)';
        UUID = NewGuid();
        String URLinstanceID = ApexPages.currentPage().getParameters().get('instanceID');
        if (!String.isBlank(URLinstanceID)) {
            evtInfo = [
                    SELECT Event_Name__c, Start_Date_Time__c, End_Date_Time__c, Instance_Title__c, Instance_Short_Description__c, Event__r.Event_Short_Listing_Description__c,
                            EVent__r.Event_description__c, Location_Title_Override__c, Event__r.Location_Title__c
                    FROM UST_Event_Instance__c
                    WHERE Id = :URLinstanceID
            ];

            if (evtInfo.size() > 0) {
                DTSTART = evtInfo[0].Start_Date_Time__c.format('yyyyMMdd\'T\'HHmmss\'Z\'');
                DTEND = evtInfo[0].End_Date_Time__c.format('yyyyMMdd\'T\'HHmmss\'Z\'');
                DTSTAMP = Datetime.now().format('yyyyMMdd\'T\'HHmmss\'Z\'');
                DESCRIPTION = evtInfo[0].Event_Name__c;
                if (!String.isBlank(evtInfo[0].Instance_Title__c)) {
                    DESCRIPTION += ' - ' + evtInfo[0].Instance_Title__c;
                }
                LONGDESCRIPTION = DESCRIPTION + evtInfo[0].Event__r.Event_description__c;
                DESCRIPTION += '\n' + evtInfo[0].Event__r.Event_Short_Listing_Description__c;
                DESCRIPTION += '\n' + evtInfo[0].Instance_Short_Description__c;
                if (String.isNotBlank(evtInfo[0].Location_Title_Override__c)) {
                    LOCATION = evtInfo[0].Location_Title_Override__c;
                } else if (String.isNotBlank(evtInfo[0].Event__r.Location_Title__c)){
                    LOCATION = evtInfo[0].Event__r.Location_Title__c;
                }

            }
        }
    }


    private static String kHexChars = '0123456789abcdef';

    public static String NewGuid() {

        String returnValue = '';
        Integer nextByte = 0;

        for (Integer i = 0; i < 16; i++) {

            if (i == 4 || i == 6 || i == 8 || i == 10)
                returnValue += '-';

            nextByte = (Math.round(Math.random() * 255) - 128) & 255;

            if (i == 6) {
                nextByte = nextByte & 15;
                nextByte = nextByte | (4 << 4);
            }

            if (i == 8) {
                nextByte = nextByte & 63;
                nextByte = nextByte | 128;
            }

            returnValue += getCharAtIndex(kHexChars, nextByte >> 4);
            returnValue += getCharAtIndex(kHexChars, nextByte & 15);
        }

        return returnValue;
    }

    public static String getCharAtIndex(String str, Integer index) {
        if (str == null) return null;
        if (str.length() <= 0) return str;
        if (index == str.length()) return null;
        return str.substring(index, index + 1);
    }
}


//http://dev-stthomas.cs65.force.com/applicantportal/usteventaddtocalendar?instanceID=a320m0000001I34