src/objects/UST_Event_Appointments__c.object
<CustomObject>
    <description>The appointments and details related to the Event Registration (e.g. Classroom visits, Lunch, Coach Visit, etc.)</description>
    <fields>
        <fullName>Appointment_Status__c</fullName>
        <inlineHelpText>The current status of the Appointment</inlineHelpText>
        <label>Appointment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Pending First Request</fullName>
                </value>
                <value>
                    <fullName>Pending Second Request</fullName>
                </value>
                <value>
                    <fullName>Pending Final Request</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Appointment_Time_Formatted__c</fullName>
        <formula>TEXT(
     IF((HOUR(Appointment_Time__c) &gt; 12),
          HOUR(Appointment_Time__c) - 12, 
          IF(HOUR(Appointment_Time__c) == 0, 12, HOUR(Appointment_Time__c))
     )

) 
&amp;
IF(!ISBLANK(HOUR(Appointment_Time__c)),&apos;:&apos;,&apos;&apos;) 
&amp;
IF(MINUTE(Appointment_Time__c)&lt;10,&apos;0&apos;,&apos;&apos;)
&amp;
TEXT(
     MINUTE(Appointment_Time__c)
)
&amp;
IF(!ISBLANK(MINUTE(Appointment_Time__c)),&apos; &apos;,&apos;&apos;) 
&amp;
IF(!ISBLANK(HOUR(Appointment_Time__c)),
     IF(HOUR(Appointment_Time__c) &gt;= 12, &apos;PM&apos;, &apos;AM&apos;), &apos;&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Appointment Time Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appointment_Time__c</fullName>
        <label>Appointment Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Appointment_Title__c</fullName>
        <description>Display title of appointment</description>
        <inlineHelpText>Display title of appointment</inlineHelpText>
        <label>Appointment Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Registration__c</fullName>
        <label>Event Registration</label>
        <referenceTo>UST_Event_Registration__c</referenceTo>
        <relationshipName>UG_Event_Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Faculty_Staff_Member__c</fullName>
        <label>Faculty/Staff Member</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>UST Event Appointment</label>
    <nameField>
        <displayFormat>APPT-{000000}</displayFormat>
        <label>Event Appointments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UST_Event_Registration__c.object
<CustomObject>
    <description>Object to contain the parent Visit/Event registration infromation and become a parent to the related Appointments</description>
    <fields>
        <fullName>Generated_Itinerary__c</fullName>
        <description>Auto generated itinerary based on confirmed appointments.</description>
        <inlineHelpText>Auto generated itinerary based on confirmed appointments.</inlineHelpText>
        <label>Generated Itinerary</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>UST Event Registration</label>
    <nameField>
        <displayFormat>EVR-{000000}</displayFormat>
        <label>Campus Event Registration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UST Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/USTEventAppointmentTriggerHandler.cls
/**
 * Created by dahl3702 on 9/28/2018.
 */

public with sharing class USTEventAppointmentTriggerHandler implements ITrigger {
    public USTEventAppointmentTriggerHandler() {

    }

    public void beforeInsert() {

    }

    public void afterInsert() {
        getUniqueRegistrationIDs(Trigger.New);
    }

    public void beforeUpdate() {

    }

    public void afterUpdate() {
        getUniqueRegistrationIDs(Trigger.New);
    }

    public void beforeDelete() {

    }

    public void afterDelete() {
        getUniqueRegistrationIDs(Trigger.old);
    }

    public void beforeUndelete() {

    }

    public void afterUnDelete() {
        getUniqueRegistrationIDs(Trigger.old);
    }

    public void bulkBefore() {

    }

    public void bulkAfter() {

    }

    public void andFinally() {

    }

    private void getUniqueRegistrationIDs(List<UST_Event_Appointments__c> newAppts) {
        //Create a mapped list of unique ids
        Map<String, String> uniqueRegIds = new Map<String, String>();
        for (UST_Event_Appointments__c na : newAppts) {
            uniqueRegIds.put(na.Event_Registration__c, na.Event_Registration__c);
        }

        List<UST_Event_Appointments__c> AllAppts = [
                SELECT Id, Name, Appointment_Time__c, Appointment_Time_Formatted__c, Event_Registration__r.Id, Appointment_Status__c,
                        Faculty_Staff_Member__c, Appointment_Title__c
                FROM UST_Event_Appointments__c
                WHERE Event_Registration__r.Id IN :uniqueRegIds.values()
                ORDER BY Event_Registration__r.Id, Appointment_Time__c
        ];

        List<UST_Event_Registration__c> newItineraryRegs = new List<UST_Event_Registration__c>();
        String generatedItinerary = '';
        String tableHead = '<tr>';
        tableHead += '<th align="left" style="text-align:left;">Time</th>';
        tableHead += '<th align="left" style="text-align:left;">Description</th>';
        tableHead += '</tr>';
        if (AllAppts.size() > 0) {
            String lastID = AllAppts[0].Id;
            for (Integer i = 0; i < AllAppts.size(); i++) {
                if ((AllAppts[i].Event_Registration__r.Id != lastId && i != 0)) {
                    if (!String.isBlank(generatedItinerary)) {
                        generatedItinerary = '<table>' + tableHead + generatedItinerary + '</table>';
                    }
                    newItineraryRegs.add(new UST_Event_Registration__c(id = AllAppts[i - 1].Event_Registration__r.Id, Generated_Itinerary__c = generatedItinerary));
                    generatedItinerary = '';
                }
                if (allAppts[i].Appointment_Status__c == 'Confirmed') {
                    generatedItinerary += '<tr>';
                    generatedItinerary += '<td style="text-align:left;">' + AllAppts[i].Appointment_Time_Formatted__c + '</td>';
                    generatedItinerary += '<td style="text-align:left;">' + AllAppts[i].Appointment_Title__c;
                    if (!String.isBlank(AllAppts[i].Faculty_Staff_Member__c)) {
                        generatedItinerary += ' - ' + AllAppts[i].Faculty_Staff_Member__c;
                    }
                    generatedItinerary += '</td>';
                    generatedItinerary += '</tr>';
                }
                lastId = AllAppts[i].Event_Registration__r.Id;

            }
            if (!String.isBlank(generatedItinerary)) {
                generatedItinerary = '<table>' + tableHead + generatedItinerary + '</table>';
            }
            newItineraryRegs.add(new UST_Event_Registration__c(id = AllAppts[AllAppts.size()-1].Event_Registration__r.Id, Generated_Itinerary__c = generatedItinerary));

            upsert newItineraryRegs;
        }
    }
}